# Starter pipeline
trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@4
    inputs:
      azureSubscription: 'Azure for Students Starter(40f7336a-173f-4235-b540-1f8b0d1ad526)'
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  # First script task
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  # Second script task
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
